### ISSUE TITLE
Pi4+NCS2 setup fail

### ISSUE THREAD

**Issue by rohanrehman** [movidius/ncappzoo#358]
make install_deps  step ok
```
./install_deps.sh
Checking system dependencies...\n
Intel Distribution of OpenVINO is installed.
Python3, pip3, git, and essential compilers are installed.
networkx             2.3
tensorflow           1.14.0
tensorflow-estimator 1.14.0
Minimal Python packages installed
ncappzoo is ready.
```
make run on "simple_classifier_cpp_camera" >>
error during
```
googlenet_v1: Compiling model to IR...
Intel OpenVINO environment is already set!
/bin/sh: 5: mo.py: not found
make[1]: *** [Makefile:68: compile_model] Error 127
make[1]: Leaving directory '/home/pi/ncappzoo/networks/googlenet_v1'
 - Copying IR files to project directory
cp: cannot stat 'googlenet-v1.bin': No such file or directory
cp: cannot stat 'googlenet-v1.xml': No such file or directory
make: *** [Makefile:36: compile_default_model] Error 1
```

adding dldt as per readme

```
export PATH=~/dldt/model-optimizer:$PATH
export PYTHONPATH=~/dldt/model-optmizer:$PYTHONPATH
```

make run on "simple_classifier_cpp_camera">>

```
googlenet_v1: Compiling model to IR...
Intel OpenVINO environment is already set!
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/home/pi/ncappzoo/networks/googlenet_v1/../../omz/open_model_zoo/tools/downloader/classification/googlenet/v1/caffe/googlenet-v1.caffemodel
	- Path for generated IR: 	/home/pi/ncappzoo/networks/googlenet_v1/.
	- IR output name: 	googlenet-v1
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	[104,117,123]
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP16
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	False
	- Reverse input channels: 	False
Caffe specific parameters:
	- Path to Python Caffe* parser generated from caffe.proto: 	/home/pi/dldt/model-optimizer/mo/front/caffe/proto
	- Enable resnet optimization: 	True
	- Path to the Input prototxt: 	/home/pi/ncappzoo/networks/googlenet_v1/../../omz/open_model_zoo/tools/downloader/classification/googlenet/v1/caffe/googlenet-v1.prototxt
	- Path to CustomLayersMapping.xml: 	Default
	- Path to a mean file: 	Not specified
	- Offsets for a mean file: 	Not specified
Model Optimizer version: 	unknown version
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  No module named 'generator'
[ ERROR ]  Traceback (most recent call last):
  File "/home/pi/dldt/model-optimizer/mo/main.py", line 298, in main
    return driver(argv)
  File "/home/pi/dldt/model-optimizer/mo/main.py", line 252, in driver
    import_extensions.load_dirs(argv.framework, extensions, get_front_classes)
  File "/home/pi/dldt/model-optimizer/mo/utils/import_extensions.py", line 102, in load_dirs
    load_dir(framework, path, get_front_classes)
  File "/home/pi/dldt/model-optimizer/mo/utils/import_extensions.py", line 87, in load_dir
    import_by_path(os.path.join(path, *p), [ext, *p])
  File "/home/pi/dldt/model-optimizer/mo/utils/import_extensions.py", line 32, in import_by_path
    importlib.import_module('{}.{}'.format('.'.join(middle_names), name))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/dldt/model-optimizer/mo/ops/expand_dims_test.py", line 20, in <module>
    from generator import generator, generate
ModuleNotFoundError: No module named 'generator'

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
make[1]: *** [Makefile:68: compile_model] Error 1
make[1]: Leaving directory '/home/pi/ncappzoo/networks/googlenet_v1'
 - Copying IR files to project directory
cp: cannot stat 'googlenet-v1.bin': No such file or directory
cp: cannot stat 'googlenet-v1.xml': No such file or directory
make: *** [Makefile:36: compile_default_model] Error 1
```

**Comment by DrewBearly** [comment]
That module is included in the test-generator package which should have been installed by one of the other Python modules needed by the Model Optimizer. Make sure to install the modules in dldt/model-optimizer/requirements.txt (or the requirements file for your framework of choice, in this case Caffe). You can 
`pip3 install -r requirements_caffe.txt`
to quickly use the requirements file with pip. Do note that the Model Optimizer isn't officially supported on ARM devices, and we've only seen Caffe-specific and Tensorflow packages available for them, so you may have to optimize models on a different machine and copy them over to use on the Raspberry pi.
